name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install TFLint
        run: |
          curl -Lo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.29.0/tflint_linux_amd64.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/
          tflint --version  # Confirm the TFLint installation

      - name: Run TFLint
        run: tflint
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform fmt
        run: terraform fmt
        working-directory: terraform

      - name: Terraform validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan -var="account_id=${{ secrets.ACCOUNT_ID }}" # Pass the account_id directly here
        working-directory: terraform

      - name: Terraform apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main'
        working-directory: terraform

        env:
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }} # This will ensure the account_id from secrets is passed to the Terraform configuration
